#!/usr/bin/env bash

npm i
npx "@bookshop/generate"
npx rosey generate --source public
node utils/generateLocales.js

if [[ $TRANSLATE == "true" ]];
then
  echo "Translating site with Rosey"
  # There's a little bit of shuffling around here to ensure the translated site ends up where CloudCannon picks up your site
  mv ./public ./untranslated_site                  
  npx rosey@latest build --source untranslated_site --dest public
fi